"""empty message

Revision ID: 189ba0923a6f
Revises: 914e4afcb017
Create Date: 2016-03-09 21:13:31.813000

"""

# revision identifiers, used by Alembic.
revision = '189ba0923a6f'
down_revision = '914e4afcb017'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'confirmed')
    ### end Alembic commands ###
