"""empty message

Revision ID: 284e81eb757b
Revises: 8476653ef090
Create Date: 2016-03-15 22:17:41.382000

"""

# revision identifiers, used by Alembic.
revision = '284e81eb757b'
down_revision = '8476653ef090'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('user_table', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user_table', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('user_table', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('user_table', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'name')
    op.drop_column('user_table', 'member_since')
    op.drop_column('user_table', 'location')
    op.drop_column('user_table', 'last_seen')
    op.drop_column('user_table', 'about_me')
    ### end Alembic commands ###
