"""empty message

Revision ID: a453398019fb
Revises: dee3f829f690
Create Date: 2016-04-03 14:34:54.935000

"""

# revision identifiers, used by Alembic.
revision = 'a453398019fb'
down_revision = 'dee3f829f690'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_table_timestamp'), 'comment_table', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_table_timestamp'), table_name='comment_table')
    op.drop_table('comment_table')
    ### end Alembic commands ###
