"""empty message

Revision ID: dc5be5759b8a
Revises: e191ae6fa63b
Create Date: 2016-03-27 15:03:09.603000

"""

# revision identifiers, used by Alembic.
revision = 'dc5be5759b8a'
down_revision = 'e191ae6fa63b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_table', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_table', 'body_html')
    ### end Alembic commands ###
