"""empty message

Revision ID: dee3f829f690
Revises: dc5be5759b8a
Create Date: 2016-03-27 19:12:05.658000

"""

# revision identifiers, used by Alembic.
revision = 'dee3f829f690'
down_revision = 'dc5be5759b8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user_table.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow')
    ### end Alembic commands ###
