"""empty message

Revision ID: e191ae6fa63b
Revises: None
Create Date: 2016-03-22 22:22:40.095000

"""

# revision identifiers, used by Alembic.
revision = 'e191ae6fa63b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('RoleName', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('RoleName')
    )
    op.create_index(op.f('ix_role_table_default'), 'role_table', ['default'], unique=False)
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('UserName', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_table_UserName'), 'user_table', ['UserName'], unique=True)
    op.create_index(op.f('ix_user_table_email'), 'user_table', ['email'], unique=True)
    op.create_table('post_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_table_timestamp'), 'post_table', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_table_timestamp'), table_name='post_table')
    op.drop_table('post_table')
    op.drop_index(op.f('ix_user_table_email'), table_name='user_table')
    op.drop_index(op.f('ix_user_table_UserName'), table_name='user_table')
    op.drop_table('user_table')
    op.drop_index(op.f('ix_role_table_default'), table_name='role_table')
    op.drop_table('role_table')
    ### end Alembic commands ###
