"""empty message

Revision ID: f0d76680075e
Revises: f4b8c52ea896
Create Date: 2016-03-21 22:02:02.753000

"""

# revision identifiers, used by Alembic.
revision = 'f0d76680075e'
down_revision = 'f4b8c52ea896'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_table_timestamp'), 'post_table', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_table_timestamp'), table_name='post_table')
    op.drop_table('post_table')
    ### end Alembic commands ###
