"""empty message

Revision ID: f4b8c52ea896
Revises: 284e81eb757b
Create Date: 2016-03-20 22:04:49.604000

"""

# revision identifiers, used by Alembic.
revision = 'f4b8c52ea896'
down_revision = '284e81eb757b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'avatar_hash')
    ### end Alembic commands ###
